import math
a = float(input())
# c = int(input())
# b = math.factorial(a)
# b = math.log10(a)
# b = math.acos(a)
# b = math.degrees(a)
# b = math.sqrt(a)
# b = math.pow(a,c)
# b = math.sin(a)
# b = math.exp(a)
# b = math.floor(a)
b = math.ceil(a)
print(b)
