tu = ('Python','Java','Android','Rahul', "bbbbb")
print(type(tu))
print(type(tu[2]))
print(tu.index("Rahul"))
print(len(tu))
print(min(tu))
print(max(tu))
print("Rahul" in tu)
b = list(tu)
b.append("Go")
print(b)
c = tuple(b)
print(c)
print(enumerate(tu))
print(tuple(enumerate(tu)))
print(list(enumerate(b)))
for i ,j in enumerate(tu):
    print(i ,"=", j)
for k in enumerate(tu):
    print(k)    
